<?xml version="1.0" encoding="UTF-8"?>
<testsuites>
	<testsuite name="test_app.AppTestCase-20240912091750" tests="2" file="test_app.py" time="0.001" timestamp="2024-09-12T09:17:50" failures="0" errors="2" skipped="0">
		<testcase classname="test_app.AppTestCase" name="test_app_exists" time="0.001" timestamp="2024-09-12T09:17:50" file="tests/test_app.py" line="11">
			<error type="TypeError" message="__init__() missing 1 required positional argument: 'key'"><![CDATA[Traceback (most recent call last):
  File "/usr/src/app/tests/base_test.py", line 21, in setUp
    self.test_jwks = TestJwk_key()
TypeError: __init__() missing 1 required positional argument: 'key'
]]></error>
		</testcase>
		<testcase classname="test_app.AppTestCase" name="test_app_is_testing" time="0.000" timestamp="2024-09-12T09:17:50" file="tests/test_app.py" line="14">
			<error type="TypeError" message="__init__() missing 1 required positional argument: 'key'"><![CDATA[Traceback (most recent call last):
  File "/usr/src/app/tests/base_test.py", line 21, in setUp
    self.test_jwks = TestJwk_key()
TypeError: __init__() missing 1 required positional argument: 'key'
]]></error>
		</testcase>
	</testsuite>
	<testsuite name="test_app.RouteIndexTestCase-20240912091750" tests="1" file="test_app.py" time="0.000" timestamp="2024-09-12T09:17:50" failures="0" errors="1" skipped="0">
		<testcase classname="test_app.RouteIndexTestCase" name="test_index_route" time="0.000" timestamp="2024-09-12T09:17:50" file="tests/test_app.py" line="19">
			<error type="TypeError" message="__init__() missing 1 required positional argument: 'key'"><![CDATA[Traceback (most recent call last):
  File "/usr/src/app/tests/base_test.py", line 21, in setUp
    self.test_jwks = TestJwk_key()
TypeError: __init__() missing 1 required positional argument: 'key'
]]></error>
		</testcase>
	</testsuite>
	<testsuite name="test_app.RouteMetaTestCase-20240912091750" tests="2" file="test_app.py" time="0.001" timestamp="2024-09-12T09:17:50" failures="0" errors="2" skipped="0">
		<testcase classname="test_app.RouteMetaTestCase" name="test_meta_healthcheck_canary_failure_db" time="0.001" timestamp="2024-09-12T09:17:50" file="tests/test_app.py" line="54">
			<error type="TypeError" message="__init__() missing 1 required positional argument: 'key'"><![CDATA[Traceback (most recent call last):
  File "/usr/src/app/tests/base_test.py", line 21, in setUp
    self.test_jwks = TestJwk_key()
TypeError: __init__() missing 1 required positional argument: 'key'
]]></error>
		</testcase>
		<testcase classname="test_app.RouteMetaTestCase" name="test_meta_healthcheck_canary_success" time="0.000" timestamp="2024-09-12T09:17:50" file="tests/test_app.py" line="36">
			<error type="TypeError" message="__init__() missing 1 required positional argument: 'key'"><![CDATA[Traceback (most recent call last):
  File "/usr/src/app/tests/base_test.py", line 21, in setUp
    self.test_jwks = TestJwk_key()
TypeError: __init__() missing 1 required positional argument: 'key'
]]></error>
		</testcase>
	</testsuite>
	<testsuite name="test_commands.ImportCommandTestCase-20240912091750" tests="3" file="test_commands.py" time="0.001" timestamp="2024-09-12T09:17:50" failures="0" errors="3" skipped="0">
		<testcase classname="test_commands.ImportCommandTestCase" name="test_import_categories_from_file" time="0.000" timestamp="2024-09-12T09:17:50" file="tests/test_commands.py" line="26">
			<error type="TypeError" message="__init__() missing 1 required positional argument: 'key'"><![CDATA[Traceback (most recent call last):
  File "/usr/src/app/tests/base_test.py", line 83, in setUp
    super().setUp()
  File "/usr/src/app/tests/base_test.py", line 21, in setUp
    self.test_jwks = TestJwk_key()
TypeError: __init__() missing 1 required positional argument: 'key'
]]></error>
		</testcase>
		<testcase classname="test_commands.ImportCommandTestCase" name="test_import_grant_from_gtr" time="0.001" timestamp="2024-09-12T09:17:50" file="tests/test_commands.py" line="34">
			<error type="TypeError" message="__init__() missing 1 required positional argument: 'key'"><![CDATA[Traceback (most recent call last):
  File "/usr/src/app/tests/base_test.py", line 83, in setUp
    super().setUp()
  File "/usr/src/app/tests/base_test.py", line 21, in setUp
    self.test_jwks = TestJwk_key()
TypeError: __init__() missing 1 required positional argument: 'key'
]]></error>
		</testcase>
		<testcase classname="test_commands.ImportCommandTestCase" name="test_import_organisations_from_file" time="0.000" timestamp="2024-09-12T09:17:50" file="tests/test_commands.py" line="30">
			<error type="TypeError" message="__init__() missing 1 required positional argument: 'key'"><![CDATA[Traceback (most recent call last):
  File "/usr/src/app/tests/base_test.py", line 83, in setUp
    super().setUp()
  File "/usr/src/app/tests/base_test.py", line 21, in setUp
    self.test_jwks = TestJwk_key()
TypeError: __init__() missing 1 required positional argument: 'key'
]]></error>
		</testcase>
	</testsuite>
	<testsuite name="test_commands.InbuiltCommandsTestCase-20240912091750" tests="1" file="test_commands.py" time="0.000" timestamp="2024-09-12T09:17:50" failures="0" errors="1" skipped="0">
		<testcase classname="test_commands.InbuiltCommandsTestCase" name="test_help" time="0.000" timestamp="2024-09-12T09:17:50" file="tests/test_commands.py" line="6">
			<error type="TypeError" message="__init__() missing 1 required positional argument: 'key'"><![CDATA[Traceback (most recent call last):
  File "/usr/src/app/tests/base_test.py", line 83, in setUp
    super().setUp()
  File "/usr/src/app/tests/base_test.py", line 21, in setUp
    self.test_jwks = TestJwk_key()
TypeError: __init__() missing 1 required positional argument: 'key'
]]></error>
		</testcase>
	</testsuite>
	<testsuite name="test_commands.SeedingCommandTestCase-20240912091750" tests="1" file="test_commands.py" time="0.000" timestamp="2024-09-12T09:17:50" failures="0" errors="1" skipped="0">
		<testcase classname="test_commands.SeedingCommandTestCase" name="test_seeding_predictable" time="0.000" timestamp="2024-09-12T09:17:50" file="tests/test_commands.py" line="12">
			<error type="TypeError" message="__init__() missing 1 required positional argument: 'key'"><![CDATA[Traceback (most recent call last):
  File "/usr/src/app/tests/base_test.py", line 83, in setUp
    super().setUp()
  File "/usr/src/app/tests/base_test.py", line 21, in setUp
    self.test_jwks = TestJwk_key()
TypeError: __init__() missing 1 required positional argument: 'key'
]]></error>
		</testcase>
	</testsuite>
	<testsuite name="test_resource_allocations.PeopleResourceTestCase-20240912091750" tests="7" file="test_resource_allocations.py" time="0.013" timestamp="2024-09-12T09:17:50" failures="0" errors="7" skipped="0">
		<testcase classname="test_resource_allocations.PeopleResourceTestCase" name="test_allocations_detail" time="0.003" timestamp="2024-09-12T09:17:50" file="tests/test_resource_allocations.py" line="411">
			<error type="TypeError" message="__init__() missing 1 required positional argument: 'key'"><![CDATA[Traceback (most recent call last):
  File "/usr/src/app/tests/base_test.py", line 61, in setUp
    super().setUp()
  File "/usr/src/app/tests/base_test.py", line 21, in setUp
    self.test_jwks = TestJwk_key()
TypeError: __init__() missing 1 required positional argument: 'key'
]]></error>
		</testcase>
		<testcase classname="test_resource_allocations.PeopleResourceTestCase" name="test_allocations_grants" time="0.001" timestamp="2024-09-12T09:17:50" file="tests/test_resource_allocations.py" line="725">
			<error type="TypeError" message="__init__() missing 1 required positional argument: 'key'"><![CDATA[Traceback (most recent call last):
  File "/usr/src/app/tests/base_test.py", line 61, in setUp
    super().setUp()
  File "/usr/src/app/tests/base_test.py", line 21, in setUp
    self.test_jwks = TestJwk_key()
TypeError: __init__() missing 1 required positional argument: 'key'
]]></error>
		</testcase>
		<testcase classname="test_resource_allocations.PeopleResourceTestCase" name="test_allocations_list" time="0.005" timestamp="2024-09-12T09:17:50" file="tests/test_resource_allocations.py" line="9">
			<error type="TypeError" message="__init__() missing 1 required positional argument: 'key'"><![CDATA[Traceback (most recent call last):
  File "/usr/src/app/tests/base_test.py", line 61, in setUp
    super().setUp()
  File "/usr/src/app/tests/base_test.py", line 21, in setUp
    self.test_jwks = TestJwk_key()
TypeError: __init__() missing 1 required positional argument: 'key'
]]></error>
		</testcase>
		<testcase classname="test_resource_allocations.PeopleResourceTestCase" name="test_allocations_projects" time="0.002" timestamp="2024-09-12T09:17:50" file="tests/test_resource_allocations.py" line="829">
			<error type="TypeError" message="__init__() missing 1 required positional argument: 'key'"><![CDATA[Traceback (most recent call last):
  File "/usr/src/app/tests/base_test.py", line 61, in setUp
    super().setUp()
  File "/usr/src/app/tests/base_test.py", line 21, in setUp
    self.test_jwks = TestJwk_key()
TypeError: __init__() missing 1 required positional argument: 'key'
]]></error>
		</testcase>
		<testcase classname="test_resource_allocations.PeopleResourceTestCase" name="test_allocations_relationship_grants" time="0.001" timestamp="2024-09-12T09:17:50" file="tests/test_resource_allocations.py" line="681">
			<error type="TypeError" message="__init__() missing 1 required positional argument: 'key'"><![CDATA[Traceback (most recent call last):
  File "/usr/src/app/tests/base_test.py", line 61, in setUp
    super().setUp()
  File "/usr/src/app/tests/base_test.py", line 21, in setUp
    self.test_jwks = TestJwk_key()
TypeError: __init__() missing 1 required positional argument: 'key'
]]></error>
		</testcase>
		<testcase classname="test_resource_allocations.PeopleResourceTestCase" name="test_allocations_relationship_projects" time="0.001" timestamp="2024-09-12T09:17:50" file="tests/test_resource_allocations.py" line="703">
			<error type="TypeError" message="__init__() missing 1 required positional argument: 'key'"><![CDATA[Traceback (most recent call last):
  File "/usr/src/app/tests/base_test.py", line 61, in setUp
    super().setUp()
  File "/usr/src/app/tests/base_test.py", line 21, in setUp
    self.test_jwks = TestJwk_key()
TypeError: __init__() missing 1 required positional argument: 'key'
]]></error>
		</testcase>
		<testcase classname="test_resource_allocations.PeopleResourceTestCase" name="test_allocations_single_missing_unknown_id" time="0.001" timestamp="2024-09-12T09:17:50" file="tests/test_resource_allocations.py" line="664">
			<error type="TypeError" message="__init__() missing 1 required positional argument: 'key'"><![CDATA[Traceback (most recent call last):
  File "/usr/src/app/tests/base_test.py", line 61, in setUp
    super().setUp()
  File "/usr/src/app/tests/base_test.py", line 21, in setUp
    self.test_jwks = TestJwk_key()
TypeError: __init__() missing 1 required positional argument: 'key'
]]></error>
		</testcase>
	</testsuite>
	<testsuite name="test_resource_categorisations.CategorisationsResourceTestCase-20240912091750" tests="7" file="test_resource_categorisations.py" time="0.016" timestamp="2024-09-12T09:17:50" failures="0" errors="7" skipped="0">
		<testcase classname="test_resource_categorisations.CategorisationsResourceTestCase" name="test_categorisations_categories" time="0.001" timestamp="2024-09-12T09:17:50" file="tests/test_resource_categorisations.py" line="1068">
			<error type="TypeError" message="__init__() missing 1 required positional argument: 'key'"><![CDATA[Traceback (most recent call last):
  File "/usr/src/app/tests/base_test.py", line 61, in setUp
    super().setUp()
  File "/usr/src/app/tests/base_test.py", line 21, in setUp
    self.test_jwks = TestJwk_key()
TypeError: __init__() missing 1 required positional argument: 'key'
]]></error>
		</testcase>
		<testcase classname="test_resource_categorisations.CategorisationsResourceTestCase" name="test_categorisations_detail" time="0.004" timestamp="2024-09-12T09:17:50" file="tests/test_resource_categorisations.py" line="550">
			<error type="TypeError" message="__init__() missing 1 required positional argument: 'key'"><![CDATA[Traceback (most recent call last):
  File "/usr/src/app/tests/base_test.py", line 61, in setUp
    super().setUp()
  File "/usr/src/app/tests/base_test.py", line 21, in setUp
    self.test_jwks = TestJwk_key()
TypeError: __init__() missing 1 required positional argument: 'key'
]]></error>
		</testcase>
		<testcase classname="test_resource_categorisations.CategorisationsResourceTestCase" name="test_categorisations_list" time="0.007" timestamp="2024-09-12T09:17:50" file="tests/test_resource_categorisations.py" line="9">
			<error type="TypeError" message="__init__() missing 1 required positional argument: 'key'"><![CDATA[Traceback (most recent call last):
  File "/usr/src/app/tests/base_test.py", line 61, in setUp
    super().setUp()
  File "/usr/src/app/tests/base_test.py", line 21, in setUp
    self.test_jwks = TestJwk_key()
TypeError: __init__() missing 1 required positional argument: 'key'
]]></error>
		</testcase>
		<testcase classname="test_resource_categorisations.CategorisationsResourceTestCase" name="test_categorisations_projects" time="0.002" timestamp="2024-09-12T09:17:50" file="tests/test_resource_categorisations.py" line="941">
			<error type="TypeError" message="__init__() missing 1 required positional argument: 'key'"><![CDATA[Traceback (most recent call last):
  File "/usr/src/app/tests/base_test.py", line 61, in setUp
    super().setUp()
  File "/usr/src/app/tests/base_test.py", line 21, in setUp
    self.test_jwks = TestJwk_key()
TypeError: __init__() missing 1 required positional argument: 'key'
]]></error>
		</testcase>
		<testcase classname="test_resource_categorisations.CategorisationsResourceTestCase" name="test_categorisations_relationship_categories" time="0.001" timestamp="2024-09-12T09:17:50" file="tests/test_resource_categorisations.py" line="919">
			<error type="TypeError" message="__init__() missing 1 required positional argument: 'key'"><![CDATA[Traceback (most recent call last):
  File "/usr/src/app/tests/base_test.py", line 61, in setUp
    super().setUp()
  File "/usr/src/app/tests/base_test.py", line 21, in setUp
    self.test_jwks = TestJwk_key()
TypeError: __init__() missing 1 required positional argument: 'key'
]]></error>
		</testcase>
		<testcase classname="test_resource_categorisations.CategorisationsResourceTestCase" name="test_categorisations_relationship_projects" time="0.001" timestamp="2024-09-12T09:17:50" file="tests/test_resource_categorisations.py" line="897">
			<error type="TypeError" message="__init__() missing 1 required positional argument: 'key'"><![CDATA[Traceback (most recent call last):
  File "/usr/src/app/tests/base_test.py", line 61, in setUp
    super().setUp()
  File "/usr/src/app/tests/base_test.py", line 21, in setUp
    self.test_jwks = TestJwk_key()
TypeError: __init__() missing 1 required positional argument: 'key'
]]></error>
		</testcase>
		<testcase classname="test_resource_categorisations.CategorisationsResourceTestCase" name="test_categorisations_single_missing_unknown_id" time="0.001" timestamp="2024-09-12T09:17:50" file="tests/test_resource_categorisations.py" line="880">
			<error type="TypeError" message="__init__() missing 1 required positional argument: 'key'"><![CDATA[Traceback (most recent call last):
  File "/usr/src/app/tests/base_test.py", line 61, in setUp
    super().setUp()
  File "/usr/src/app/tests/base_test.py", line 21, in setUp
    self.test_jwks = TestJwk_key()
TypeError: __init__() missing 1 required positional argument: 'key'
]]></error>
		</testcase>
	</testsuite>
	<testsuite name="test_resource_category_schemes.CategorySchemesResourceTestCase-20240912091750" tests="5" file="test_resource_category_schemes.py" time="0.018" timestamp="2024-09-12T09:17:50" failures="0" errors="5" skipped="0">
		<testcase classname="test_resource_category_schemes.CategorySchemesResourceTestCase" name="test_category_scheme_category_terms" time="0.004" timestamp="2024-09-12T09:17:50" file="tests/test_resource_category_schemes.py" line="1118">
			<error type="TypeError" message="__init__() missing 1 required positional argument: 'key'"><![CDATA[Traceback (most recent call last):
  File "/usr/src/app/tests/base_test.py", line 61, in setUp
    super().setUp()
  File "/usr/src/app/tests/base_test.py", line 21, in setUp
    self.test_jwks = TestJwk_key()
TypeError: __init__() missing 1 required positional argument: 'key'
]]></error>
		</testcase>
		<testcase classname="test_resource_category_schemes.CategorySchemesResourceTestCase" name="test_category_scheme_detail" time="0.005" timestamp="2024-09-12T09:17:50" file="tests/test_resource_category_schemes.py" line="661">
			<error type="TypeError" message="__init__() missing 1 required positional argument: 'key'"><![CDATA[Traceback (most recent call last):
  File "/usr/src/app/tests/base_test.py", line 61, in setUp
    super().setUp()
  File "/usr/src/app/tests/base_test.py", line 21, in setUp
    self.test_jwks = TestJwk_key()
TypeError: __init__() missing 1 required positional argument: 'key'
]]></error>
		</testcase>
		<testcase classname="test_resource_category_schemes.CategorySchemesResourceTestCase" name="test_category_scheme_list" time="0.008" timestamp="2024-09-12T09:17:50" file="tests/test_resource_category_schemes.py" line="9">
			<error type="TypeError" message="__init__() missing 1 required positional argument: 'key'"><![CDATA[Traceback (most recent call last):
  File "/usr/src/app/tests/base_test.py", line 61, in setUp
    super().setUp()
  File "/usr/src/app/tests/base_test.py", line 21, in setUp
    self.test_jwks = TestJwk_key()
TypeError: __init__() missing 1 required positional argument: 'key'
]]></error>
		</testcase>
		<testcase classname="test_resource_category_schemes.CategorySchemesResourceTestCase" name="test_category_scheme_relationship_category_terms" time="0.001" timestamp="2024-09-12T09:17:50" file="tests/test_resource_category_schemes.py" line="1082">
			<error type="TypeError" message="__init__() missing 1 required positional argument: 'key'"><![CDATA[Traceback (most recent call last):
  File "/usr/src/app/tests/base_test.py", line 61, in setUp
    super().setUp()
  File "/usr/src/app/tests/base_test.py", line 21, in setUp
    self.test_jwks = TestJwk_key()
TypeError: __init__() missing 1 required positional argument: 'key'
]]></error>
		</testcase>
		<testcase classname="test_resource_category_schemes.CategorySchemesResourceTestCase" name="test_category_scheme_single_missing_unknown_id" time="0.001" timestamp="2024-09-12T09:17:50" file="tests/test_resource_category_schemes.py" line="1065">
			<error type="TypeError" message="__init__() missing 1 required positional argument: 'key'"><![CDATA[Traceback (most recent call last):
  File "/usr/src/app/tests/base_test.py", line 61, in setUp
    super().setUp()
  File "/usr/src/app/tests/base_test.py", line 21, in setUp
    self.test_jwks = TestJwk_key()
TypeError: __init__() missing 1 required positional argument: 'key'
]]></error>
		</testcase>
	</testsuite>
	<testsuite name="test_resource_category_terms.CategoryTermsResourceTestCase-20240912091750" tests="9" file="test_resource_category_terms.py" time="0.013" timestamp="2024-09-12T09:17:50" failures="0" errors="9" skipped="0">
		<testcase classname="test_resource_category_terms.CategoryTermsResourceTestCase" name="test_category_term_categorisations" time="0.001" timestamp="2024-09-12T09:17:50" file="tests/test_resource_category_terms.py" line="802">
			<error type="TypeError" message="__init__() missing 1 required positional argument: 'key'"><![CDATA[Traceback (most recent call last):
  File "/usr/src/app/tests/base_test.py", line 61, in setUp
    super().setUp()
  File "/usr/src/app/tests/base_test.py", line 21, in setUp
    self.test_jwks = TestJwk_key()
TypeError: __init__() missing 1 required positional argument: 'key'
]]></error>
		</testcase>
		<testcase classname="test_resource_category_terms.CategoryTermsResourceTestCase" name="test_category_term_category_schemes" time="0.001" timestamp="2024-09-12T09:17:50" file="tests/test_resource_category_terms.py" line="743">
			<error type="TypeError" message="__init__() missing 1 required positional argument: 'key'"><![CDATA[Traceback (most recent call last):
  File "/usr/src/app/tests/base_test.py", line 61, in setUp
    super().setUp()
  File "/usr/src/app/tests/base_test.py", line 21, in setUp
    self.test_jwks = TestJwk_key()
TypeError: __init__() missing 1 required positional argument: 'key'
]]></error>
		</testcase>
		<testcase classname="test_resource_category_terms.CategoryTermsResourceTestCase" name="test_category_term_detail" time="0.004" timestamp="2024-09-12T09:17:50" file="tests/test_resource_category_terms.py" line="252">
			<error type="TypeError" message="__init__() missing 1 required positional argument: 'key'"><![CDATA[Traceback (most recent call last):
  File "/usr/src/app/tests/base_test.py", line 61, in setUp
    super().setUp()
  File "/usr/src/app/tests/base_test.py", line 21, in setUp
    self.test_jwks = TestJwk_key()
TypeError: __init__() missing 1 required positional argument: 'key'
]]></error>
		</testcase>
		<testcase classname="test_resource_category_terms.CategoryTermsResourceTestCase" name="test_category_term_list" time="0.003" timestamp="2024-09-12T09:17:50" file="tests/test_resource_category_terms.py" line="9">
			<error type="TypeError" message="__init__() missing 1 required positional argument: 'key'"><![CDATA[Traceback (most recent call last):
  File "/usr/src/app/tests/base_test.py", line 61, in setUp
    super().setUp()
  File "/usr/src/app/tests/base_test.py", line 21, in setUp
    self.test_jwks = TestJwk_key()
TypeError: __init__() missing 1 required positional argument: 'key'
]]></error>
		</testcase>
		<testcase classname="test_resource_category_terms.CategoryTermsResourceTestCase" name="test_category_term_parent_category_terms" time="0.001" timestamp="2024-09-12T09:17:50" file="tests/test_resource_category_terms.py" line="667">
			<error type="TypeError" message="__init__() missing 1 required positional argument: 'key'"><![CDATA[Traceback (most recent call last):
  File "/usr/src/app/tests/base_test.py", line 61, in setUp
    super().setUp()
  File "/usr/src/app/tests/base_test.py", line 21, in setUp
    self.test_jwks = TestJwk_key()
TypeError: __init__() missing 1 required positional argument: 'key'
]]></error>
		</testcase>
		<testcase classname="test_resource_category_terms.CategoryTermsResourceTestCase" name="test_category_term_relationship_categorisations" time="0.001" timestamp="2024-09-12T09:17:50" file="tests/test_resource_category_terms.py" line="643">
			<error type="TypeError" message="__init__() missing 1 required positional argument: 'key'"><![CDATA[Traceback (most recent call last):
  File "/usr/src/app/tests/base_test.py", line 61, in setUp
    super().setUp()
  File "/usr/src/app/tests/base_test.py", line 21, in setUp
    self.test_jwks = TestJwk_key()
TypeError: __init__() missing 1 required positional argument: 'key'
]]></error>
		</testcase>
		<testcase classname="test_resource_category_terms.CategoryTermsResourceTestCase" name="test_category_term_relationship_category_schemes" time="0.001" timestamp="2024-09-12T09:17:50" file="tests/test_resource_category_terms.py" line="621">
			<error type="TypeError" message="__init__() missing 1 required positional argument: 'key'"><![CDATA[Traceback (most recent call last):
  File "/usr/src/app/tests/base_test.py", line 61, in setUp
    super().setUp()
  File "/usr/src/app/tests/base_test.py", line 21, in setUp
    self.test_jwks = TestJwk_key()
TypeError: __init__() missing 1 required positional argument: 'key'
]]></error>
		</testcase>
		<testcase classname="test_resource_category_terms.CategoryTermsResourceTestCase" name="test_category_term_relationship_parent_category_terms" time="0.001" timestamp="2024-09-12T09:17:50" file="tests/test_resource_category_terms.py" line="599">
			<error type="TypeError" message="__init__() missing 1 required positional argument: 'key'"><![CDATA[Traceback (most recent call last):
  File "/usr/src/app/tests/base_test.py", line 61, in setUp
    super().setUp()
  File "/usr/src/app/tests/base_test.py", line 21, in setUp
    self.test_jwks = TestJwk_key()
TypeError: __init__() missing 1 required positional argument: 'key'
]]></error>
		</testcase>
		<testcase classname="test_resource_category_terms.CategoryTermsResourceTestCase" name="test_category_term_single_missing_unknown_id" time="0.001" timestamp="2024-09-12T09:17:50" file="tests/test_resource_category_terms.py" line="582">
			<error type="TypeError" message="__init__() missing 1 required positional argument: 'key'"><![CDATA[Traceback (most recent call last):
  File "/usr/src/app/tests/base_test.py", line 61, in setUp
    super().setUp()
  File "/usr/src/app/tests/base_test.py", line 21, in setUp
    self.test_jwks = TestJwk_key()
TypeError: __init__() missing 1 required positional argument: 'key'
]]></error>
		</testcase>
	</testsuite>
	<testsuite name="test_resource_grants.GrantsResourceTestCase-20240912091750" tests="7" file="test_resource_grants.py" time="0.013" timestamp="2024-09-12T09:17:50" failures="0" errors="7" skipped="0">
		<testcase classname="test_resource_grants.GrantsResourceTestCase" name="test_grants_allocations" time="0.001" timestamp="2024-09-12T09:17:50" file="tests/test_resource_grants.py" line="838">
			<error type="TypeError" message="__init__() missing 1 required positional argument: 'key'"><![CDATA[Traceback (most recent call last):
  File "/usr/src/app/tests/base_test.py", line 61, in setUp
    super().setUp()
  File "/usr/src/app/tests/base_test.py", line 21, in setUp
    self.test_jwks = TestJwk_key()
TypeError: __init__() missing 1 required positional argument: 'key'
]]></error>
		</testcase>
		<testcase classname="test_resource_grants.GrantsResourceTestCase" name="test_grants_detail" time="0.004" timestamp="2024-09-12T09:17:50" file="tests/test_resource_grants.py" line="487">
			<error type="TypeError" message="__init__() missing 1 required positional argument: 'key'"><![CDATA[Traceback (most recent call last):
  File "/usr/src/app/tests/base_test.py", line 61, in setUp
    super().setUp()
  File "/usr/src/app/tests/base_test.py", line 21, in setUp
    self.test_jwks = TestJwk_key()
TypeError: __init__() missing 1 required positional argument: 'key'
]]></error>
		</testcase>
		<testcase classname="test_resource_grants.GrantsResourceTestCase" name="test_grants_list" time="0.006" timestamp="2024-09-12T09:17:50" file="tests/test_resource_grants.py" line="9">
			<error type="TypeError" message="__init__() missing 1 required positional argument: 'key'"><![CDATA[Traceback (most recent call last):
  File "/usr/src/app/tests/base_test.py", line 61, in setUp
    super().setUp()
  File "/usr/src/app/tests/base_test.py", line 21, in setUp
    self.test_jwks = TestJwk_key()
TypeError: __init__() missing 1 required positional argument: 'key'
]]></error>
		</testcase>
		<testcase classname="test_resource_grants.GrantsResourceTestCase" name="test_grants_organisations" time="0.001" timestamp="2024-09-12T09:17:50" file="tests/test_resource_grants.py" line="886">
			<error type="TypeError" message="__init__() missing 1 required positional argument: 'key'"><![CDATA[Traceback (most recent call last):
  File "/usr/src/app/tests/base_test.py", line 61, in setUp
    super().setUp()
  File "/usr/src/app/tests/base_test.py", line 21, in setUp
    self.test_jwks = TestJwk_key()
TypeError: __init__() missing 1 required positional argument: 'key'
]]></error>
		</testcase>
		<testcase classname="test_resource_grants.GrantsResourceTestCase" name="test_grants_relationship_allocations" time="0.001" timestamp="2024-09-12T09:17:50" file="tests/test_resource_grants.py" line="792">
			<error type="TypeError" message="__init__() missing 1 required positional argument: 'key'"><![CDATA[Traceback (most recent call last):
  File "/usr/src/app/tests/base_test.py", line 61, in setUp
    super().setUp()
  File "/usr/src/app/tests/base_test.py", line 21, in setUp
    self.test_jwks = TestJwk_key()
TypeError: __init__() missing 1 required positional argument: 'key'
]]></error>
		</testcase>
		<testcase classname="test_resource_grants.GrantsResourceTestCase" name="test_grants_relationship_organisations" time="0.001" timestamp="2024-09-12T09:17:50" file="tests/test_resource_grants.py" line="816">
			<error type="TypeError" message="__init__() missing 1 required positional argument: 'key'"><![CDATA[Traceback (most recent call last):
  File "/usr/src/app/tests/base_test.py", line 61, in setUp
    super().setUp()
  File "/usr/src/app/tests/base_test.py", line 21, in setUp
    self.test_jwks = TestJwk_key()
TypeError: __init__() missing 1 required positional argument: 'key'
]]></error>
		</testcase>
		<testcase classname="test_resource_grants.GrantsResourceTestCase" name="test_grants_single_missing_unknown_id" time="0.001" timestamp="2024-09-12T09:17:50" file="tests/test_resource_grants.py" line="775">
			<error type="TypeError" message="__init__() missing 1 required positional argument: 'key'"><![CDATA[Traceback (most recent call last):
  File "/usr/src/app/tests/base_test.py", line 61, in setUp
    super().setUp()
  File "/usr/src/app/tests/base_test.py", line 21, in setUp
    self.test_jwks = TestJwk_key()
TypeError: __init__() missing 1 required positional argument: 'key'
]]></error>
		</testcase>
	</testsuite>
	<testsuite name="test_resource_organisations.OrganisationsResourceTestCase-20240912091750" tests="7" file="test_resource_organisations.py" time="0.015" timestamp="2024-09-12T09:17:50" failures="0" errors="7" skipped="0">
		<testcase classname="test_resource_organisations.OrganisationsResourceTestCase" name="test_organisations_detail" time="0.004" timestamp="2024-09-12T09:17:50" file="tests/test_resource_organisations.py" line="680">
			<error type="TypeError" message="__init__() missing 1 required positional argument: 'key'"><![CDATA[Traceback (most recent call last):
  File "/usr/src/app/tests/base_test.py", line 61, in setUp
    super().setUp()
  File "/usr/src/app/tests/base_test.py", line 21, in setUp
    self.test_jwks = TestJwk_key()
TypeError: __init__() missing 1 required positional argument: 'key'
]]></error>
		</testcase>
		<testcase classname="test_resource_organisations.OrganisationsResourceTestCase" name="test_organisations_grants" time="0.001" timestamp="2024-09-12T09:17:50" file="tests/test_resource_organisations.py" line="982">
			<error type="TypeError" message="__init__() missing 1 required positional argument: 'key'"><![CDATA[Traceback (most recent call last):
  File "/usr/src/app/tests/base_test.py", line 61, in setUp
    super().setUp()
  File "/usr/src/app/tests/base_test.py", line 21, in setUp
    self.test_jwks = TestJwk_key()
TypeError: __init__() missing 1 required positional argument: 'key'
]]></error>
		</testcase>
		<testcase classname="test_resource_organisations.OrganisationsResourceTestCase" name="test_organisations_list" time="0.009" timestamp="2024-09-12T09:17:50" file="tests/test_resource_organisations.py" line="9">
			<error type="TypeError" message="__init__() missing 1 required positional argument: 'key'"><![CDATA[Traceback (most recent call last):
  File "/usr/src/app/tests/base_test.py", line 61, in setUp
    super().setUp()
  File "/usr/src/app/tests/base_test.py", line 21, in setUp
    self.test_jwks = TestJwk_key()
TypeError: __init__() missing 1 required positional argument: 'key'
]]></error>
		</testcase>
		<testcase classname="test_resource_organisations.OrganisationsResourceTestCase" name="test_organisations_people" time="0.001" timestamp="2024-09-12T09:17:50" file="tests/test_resource_organisations.py" line="1000">
			<error type="TypeError" message="__init__() missing 1 required positional argument: 'key'"><![CDATA[Traceback (most recent call last):
  File "/usr/src/app/tests/base_test.py", line 61, in setUp
    super().setUp()
  File "/usr/src/app/tests/base_test.py", line 21, in setUp
    self.test_jwks = TestJwk_key()
TypeError: __init__() missing 1 required positional argument: 'key'
]]></error>
		</testcase>
		<testcase classname="test_resource_organisations.OrganisationsResourceTestCase" name="test_organisations_relationship_grants" time="0.001" timestamp="2024-09-12T09:17:50" file="tests/test_resource_organisations.py" line="939">
			<error type="TypeError" message="__init__() missing 1 required positional argument: 'key'"><![CDATA[Traceback (most recent call last):
  File "/usr/src/app/tests/base_test.py", line 61, in setUp
    super().setUp()
  File "/usr/src/app/tests/base_test.py", line 21, in setUp
    self.test_jwks = TestJwk_key()
TypeError: __init__() missing 1 required positional argument: 'key'
]]></error>
		</testcase>
		<testcase classname="test_resource_organisations.OrganisationsResourceTestCase" name="test_organisations_relationship_people" time="0.001" timestamp="2024-09-12T09:17:50" file="tests/test_resource_organisations.py" line="958">
			<error type="TypeError" message="__init__() missing 1 required positional argument: 'key'"><![CDATA[Traceback (most recent call last):
  File "/usr/src/app/tests/base_test.py", line 61, in setUp
    super().setUp()
  File "/usr/src/app/tests/base_test.py", line 21, in setUp
    self.test_jwks = TestJwk_key()
TypeError: __init__() missing 1 required positional argument: 'key'
]]></error>
		</testcase>
		<testcase classname="test_resource_organisations.OrganisationsResourceTestCase" name="test_organisations_single_missing_unknown_id" time="0.001" timestamp="2024-09-12T09:17:50" file="tests/test_resource_organisations.py" line="922">
			<error type="TypeError" message="__init__() missing 1 required positional argument: 'key'"><![CDATA[Traceback (most recent call last):
  File "/usr/src/app/tests/base_test.py", line 61, in setUp
    super().setUp()
  File "/usr/src/app/tests/base_test.py", line 21, in setUp
    self.test_jwks = TestJwk_key()
TypeError: __init__() missing 1 required positional argument: 'key'
]]></error>
		</testcase>
	</testsuite>
	<testsuite name="test_resource_participants.ParticipantsResourceTestCase-20240912091750" tests="7" file="test_resource_participants.py" time="0.011" timestamp="2024-09-12T09:17:50" failures="0" errors="7" skipped="0">
		<testcase classname="test_resource_participants.ParticipantsResourceTestCase" name="test_participants_detail" time="0.003" timestamp="2024-09-12T09:17:50" file="tests/test_resource_participants.py" line="295">
			<error type="TypeError" message="__init__() missing 1 required positional argument: 'key'"><![CDATA[Traceback (most recent call last):
  File "/usr/src/app/tests/base_test.py", line 61, in setUp
    super().setUp()
  File "/usr/src/app/tests/base_test.py", line 21, in setUp
    self.test_jwks = TestJwk_key()
TypeError: __init__() missing 1 required positional argument: 'key'
]]></error>
		</testcase>
		<testcase classname="test_resource_participants.ParticipantsResourceTestCase" name="test_participants_list" time="0.004" timestamp="2024-09-12T09:17:50" file="tests/test_resource_participants.py" line="9">
			<error type="TypeError" message="__init__() missing 1 required positional argument: 'key'"><![CDATA[Traceback (most recent call last):
  File "/usr/src/app/tests/base_test.py", line 61, in setUp
    super().setUp()
  File "/usr/src/app/tests/base_test.py", line 21, in setUp
    self.test_jwks = TestJwk_key()
TypeError: __init__() missing 1 required positional argument: 'key'
]]></error>
		</testcase>
		<testcase classname="test_resource_participants.ParticipantsResourceTestCase" name="test_participants_people" time="0.001" timestamp="2024-09-12T09:17:50" file="tests/test_resource_participants.py" line="689">
			<error type="TypeError" message="__init__() missing 1 required positional argument: 'key'"><![CDATA[Traceback (most recent call last):
  File "/usr/src/app/tests/base_test.py", line 61, in setUp
    super().setUp()
  File "/usr/src/app/tests/base_test.py", line 21, in setUp
    self.test_jwks = TestJwk_key()
TypeError: __init__() missing 1 required positional argument: 'key'
]]></error>
		</testcase>
		<testcase classname="test_resource_participants.ParticipantsResourceTestCase" name="test_participants_projects" time="0.002" timestamp="2024-09-12T09:17:50" file="tests/test_resource_participants.py" line="562">
			<error type="TypeError" message="__init__() missing 1 required positional argument: 'key'"><![CDATA[Traceback (most recent call last):
  File "/usr/src/app/tests/base_test.py", line 61, in setUp
    super().setUp()
  File "/usr/src/app/tests/base_test.py", line 21, in setUp
    self.test_jwks = TestJwk_key()
TypeError: __init__() missing 1 required positional argument: 'key'
]]></error>
		</testcase>
		<testcase classname="test_resource_participants.ParticipantsResourceTestCase" name="test_participants_relationship_people" time="0.001" timestamp="2024-09-12T09:17:50" file="tests/test_resource_participants.py" line="540">
			<error type="TypeError" message="__init__() missing 1 required positional argument: 'key'"><![CDATA[Traceback (most recent call last):
  File "/usr/src/app/tests/base_test.py", line 61, in setUp
    super().setUp()
  File "/usr/src/app/tests/base_test.py", line 21, in setUp
    self.test_jwks = TestJwk_key()
TypeError: __init__() missing 1 required positional argument: 'key'
]]></error>
		</testcase>
		<testcase classname="test_resource_participants.ParticipantsResourceTestCase" name="test_participants_relationship_projects" time="0.001" timestamp="2024-09-12T09:17:50" file="tests/test_resource_participants.py" line="518">
			<error type="TypeError" message="__init__() missing 1 required positional argument: 'key'"><![CDATA[Traceback (most recent call last):
  File "/usr/src/app/tests/base_test.py", line 61, in setUp
    super().setUp()
  File "/usr/src/app/tests/base_test.py", line 21, in setUp
    self.test_jwks = TestJwk_key()
TypeError: __init__() missing 1 required positional argument: 'key'
]]></error>
		</testcase>
		<testcase classname="test_resource_participants.ParticipantsResourceTestCase" name="test_participants_single_missing_unknown_id" time="0.001" timestamp="2024-09-12T09:17:50" file="tests/test_resource_participants.py" line="501">
			<error type="TypeError" message="__init__() missing 1 required positional argument: 'key'"><![CDATA[Traceback (most recent call last):
  File "/usr/src/app/tests/base_test.py", line 61, in setUp
    super().setUp()
  File "/usr/src/app/tests/base_test.py", line 21, in setUp
    self.test_jwks = TestJwk_key()
TypeError: __init__() missing 1 required positional argument: 'key'
]]></error>
		</testcase>
	</testsuite>
	<testsuite name="unittest.loader._FailedTest-20240912091750" tests="1" file="unittest/loader.py" time="0.000" timestamp="2024-09-12T09:17:50" failures="0" errors="1" skipped="0">
		<testcase classname="unittest.loader._FailedTest" name="test_resource_people" time="0.000" timestamp="2024-09-12T09:17:50" file="/usr/local/lib/python3.9/unittest/loader.py" line="33">
			<error type="ImportError" message="Failed to import test module: test_resource_people
Traceback (most recent call last):
  File &quot;/usr/local/lib/python3.9/unittest/loader.py&quot;, line 436, in _find_test_path
    module = self._get_module_from_name(name)
  File &quot;/usr/local/lib/python3.9/unittest/loader.py&quot;, line 377, in _get_module_from_name
    __import__(name)
  File &quot;/usr/src/app/tests/test_resource_people.py&quot;, line 3, in &lt;module&gt;
    from flask_azure_oauth.mocks.tokens import TestJwt
ModuleNotFoundError: No module named 'flask_azure_oauth'
"><![CDATA[ImportError: Failed to import test module: test_resource_people
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/unittest/loader.py", line 436, in _find_test_path
    module = self._get_module_from_name(name)
  File "/usr/local/lib/python3.9/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/usr/src/app/tests/test_resource_people.py", line 3, in <module>
    from flask_azure_oauth.mocks.tokens import TestJwt
ModuleNotFoundError: No module named 'flask_azure_oauth'

]]></error>
		</testcase>
	</testsuite>
	<testsuite name="test_resource_projects.ProjectsResourceTestCase-20240912091750" tests="9" file="test_resource_projects.py" time="0.026" timestamp="2024-09-12T09:17:50" failures="0" errors="9" skipped="0">
		<testcase classname="test_resource_projects.ProjectsResourceTestCase" name="test_projects_allocations" time="0.001" timestamp="2024-09-12T09:17:50" file="tests/test_resource_projects.py" line="1618">
			<error type="TypeError" message="__init__() missing 1 required positional argument: 'key'"><![CDATA[Traceback (most recent call last):
  File "/usr/src/app/tests/base_test.py", line 61, in setUp
    super().setUp()
  File "/usr/src/app/tests/base_test.py", line 21, in setUp
    self.test_jwks = TestJwk_key()
TypeError: __init__() missing 1 required positional argument: 'key'
]]></error>
		</testcase>
		<testcase classname="test_resource_projects.ProjectsResourceTestCase" name="test_projects_categorisations" time="0.001" timestamp="2024-09-12T09:17:50" file="tests/test_resource_projects.py" line="1759">
			<error type="TypeError" message="__init__() missing 1 required positional argument: 'key'"><![CDATA[Traceback (most recent call last):
  File "/usr/src/app/tests/base_test.py", line 61, in setUp
    super().setUp()
  File "/usr/src/app/tests/base_test.py", line 21, in setUp
    self.test_jwks = TestJwk_key()
TypeError: __init__() missing 1 required positional argument: 'key'
]]></error>
		</testcase>
		<testcase classname="test_resource_projects.ProjectsResourceTestCase" name="test_projects_detail" time="0.008" timestamp="2024-09-12T09:17:50" file="tests/test_resource_projects.py" line="903">
			<error type="TypeError" message="__init__() missing 1 required positional argument: 'key'"><![CDATA[Traceback (most recent call last):
  File "/usr/src/app/tests/base_test.py", line 61, in setUp
    super().setUp()
  File "/usr/src/app/tests/base_test.py", line 21, in setUp
    self.test_jwks = TestJwk_key()
TypeError: __init__() missing 1 required positional argument: 'key'
]]></error>
		</testcase>
		<testcase classname="test_resource_projects.ProjectsResourceTestCase" name="test_projects_list" time="0.012" timestamp="2024-09-12T09:17:50" file="tests/test_resource_projects.py" line="9">
			<error type="TypeError" message="__init__() missing 1 required positional argument: 'key'"><![CDATA[Traceback (most recent call last):
  File "/usr/src/app/tests/base_test.py", line 61, in setUp
    super().setUp()
  File "/usr/src/app/tests/base_test.py", line 21, in setUp
    self.test_jwks = TestJwk_key()
TypeError: __init__() missing 1 required positional argument: 'key'
]]></error>
		</testcase>
		<testcase classname="test_resource_projects.ProjectsResourceTestCase" name="test_projects_participants" time="0.001" timestamp="2024-09-12T09:17:50" file="tests/test_resource_projects.py" line="1666">
			<error type="TypeError" message="__init__() missing 1 required positional argument: 'key'"><![CDATA[Traceback (most recent call last):
  File "/usr/src/app/tests/base_test.py", line 61, in setUp
    super().setUp()
  File "/usr/src/app/tests/base_test.py", line 21, in setUp
    self.test_jwks = TestJwk_key()
TypeError: __init__() missing 1 required positional argument: 'key'
]]></error>
		</testcase>
		<testcase classname="test_resource_projects.ProjectsResourceTestCase" name="test_projects_relationship_allocations" time="0.001" timestamp="2024-09-12T09:17:50" file="tests/test_resource_projects.py" line="1542">
			<error type="TypeError" message="__init__() missing 1 required positional argument: 'key'"><![CDATA[Traceback (most recent call last):
  File "/usr/src/app/tests/base_test.py", line 61, in setUp
    super().setUp()
  File "/usr/src/app/tests/base_test.py", line 21, in setUp
    self.test_jwks = TestJwk_key()
TypeError: __init__() missing 1 required positional argument: 'key'
]]></error>
		</testcase>
		<testcase classname="test_resource_projects.ProjectsResourceTestCase" name="test_projects_relationship_categorisations" time="0.001" timestamp="2024-09-12T09:17:50" file="tests/test_resource_projects.py" line="1594">
			<error type="TypeError" message="__init__() missing 1 required positional argument: 'key'"><![CDATA[Traceback (most recent call last):
  File "/usr/src/app/tests/base_test.py", line 61, in setUp
    super().setUp()
  File "/usr/src/app/tests/base_test.py", line 21, in setUp
    self.test_jwks = TestJwk_key()
TypeError: __init__() missing 1 required positional argument: 'key'
]]></error>
		</testcase>
		<testcase classname="test_resource_projects.ProjectsResourceTestCase" name="test_projects_relationship_participants" time="0.001" timestamp="2024-09-12T09:17:50" file="tests/test_resource_projects.py" line="1566">
			<error type="TypeError" message="__init__() missing 1 required positional argument: 'key'"><![CDATA[Traceback (most recent call last):
  File "/usr/src/app/tests/base_test.py", line 61, in setUp
    super().setUp()
  File "/usr/src/app/tests/base_test.py", line 21, in setUp
    self.test_jwks = TestJwk_key()
TypeError: __init__() missing 1 required positional argument: 'key'
]]></error>
		</testcase>
		<testcase classname="test_resource_projects.ProjectsResourceTestCase" name="test_projects_single_missing_unknown_id" time="0.001" timestamp="2024-09-12T09:17:50" file="tests/test_resource_projects.py" line="1525">
			<error type="TypeError" message="__init__() missing 1 required positional argument: 'key'"><![CDATA[Traceback (most recent call last):
  File "/usr/src/app/tests/base_test.py", line 61, in setUp
    super().setUp()
  File "/usr/src/app/tests/base_test.py", line 21, in setUp
    self.test_jwks = TestJwk_key()
TypeError: __init__() missing 1 required positional argument: 'key'
]]></error>
		</testcase>
	</testsuite>
</testsuites>
